apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "adminer.fullname" . }}
  labels:
    {{- include "adminer.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  gateways:
    - {{ .Values.global.ingressGatewayName | quote }}
    - "adminer-gateway"
  hosts:
    - "adminer.{{ .Values.global.externalHostname }}"
  http:
    - match:
{{- range .Values.ingressGateway.matchPrefix }}
      - uri:
          prefix: {{ . | quote }}
{{- end }}
      route:
      - destination:
          host: {{ .Values.service.name | quote }}
          subset: {{ (print "v" .Values.version) | quote }}
{{- if .Values.retries }}
      retries:
{{ toYaml .Values.retries | indent 8 }}
      timeout: {{ required "You must specify an overall timeout to use retries" .Values.overallTimeout }}
{{- else if .Values.overallTimeout }}
      timeout: {{ .Values.overallTimeout }}
{{- end }}
