---
__secrets_file: "{{ workspace_secrets_dir }}/kaigara_secrets.yml"

__deposit_address_grpc_addr: "{{ service_names.peatio }}-stream-daemon:{{ service_ports.deposit_address }}"
__withdraw_grpc_addr: "{{ service_names.peatio }}-stream-daemon:{{ service_ports.withdraw }}"
__trade_executor_grpc_addr: "{{ service_names.peatio }}-stream-daemon:{{ service_ports.trade_executor }}"
__order_processor_grpc_addr: "{{ service_names.peatio }}-stream-daemon:{{ service_ports.order_processor }}"
__matching_grpc_addr: "{{ service_names.peatio }}-stream-daemon:{{ service_ports.matching }}"
__code_grpc_addr: "{{ service_names.peatio }}-stream-daemon:{{ service_ports.code }}"
__p2p_grpc_addr: "{{ service_names.peatio }}-stream-daemon:{{ service_ports.p2p }}"
__conversation_grpc_addr: "{{ service_names.peatio }}-stream-daemon:{{ service_ports.conversation }}"
__notify_grpc_addr: "{{ service_names.peatio }}-stream-daemon:{{ service_ports.notify }}"
__activity_recorder_grpc_addr: "{{ service_names.barong }}-stream-daemon:{{ service_ports.activity_recorder }}"
__runner_grpc_addr: "{{ service_names.quantex }}-stream-daemon:{{ service_ports.quantex_runner }}"
_peatio_grpc_addr: "{{ service_names.peatio }}:{{ service_ports.peatio_grpc }}"
