---
- name: Stage 2 - Setup vault
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    vault_internal_ip: vault.k8s-learn.com
    vault_api_port: 80
    vault_api_protocol: http
  roles:
    - database
    - vault
